(display (* 3 3.0))
(newline)
(display (+ 3 3.0))
(newline)
(display (- 3 3.0))
(newline)
(display (/ 3 3.0))
(newline)
(display (* 3 3))
(newline)
(display (+ 3 3))
(newline)
(display (- 3 3))
(newline)
(display (/ 3 3))
(newline)
(display (* 3.0 3.0))
(newline)
(display (+ 3.0 3.0))
(newline)
(display (- 3.0 3.0))
(newline)
(display (/ 3.0 3.0))
(newline)
