// generated by Fast Light User Interface Designer (fluid) version 1.0300
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

void make_numpad_window(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(120, 160);
    w = o;
    { Fl_Button* o = new Fl_Button(0, 0, 40, 40, "9");
      o->tooltip("9");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(40, 0, 40, 40, "8");
      o->tooltip("8");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(80, 0, 40, 40, "7");
      o->tooltip("7");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(0, 40, 40, 40, "6");
      o->tooltip("6");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(40, 40, 40, 40, "5");
      o->tooltip("5");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(80, 40, 40, 40, "4");
      o->tooltip("4");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(0, 80, 40, 40, "3");
      o->tooltip("3");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(40, 80, 40, 40, "2");
      o->tooltip("2");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(80, 80, 40, 40, "1");
      o->tooltip("1");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(0, 120, 80, 40, "0");
      o->tooltip("0");
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(80, 120, 40, 40, ",");
      o->tooltip(",");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o

  w->show(argc, argv);
}

int main(int argc, char **argv)
{
    make_numpad_window(argc, argv);
    return Fl::run();
}
