// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "teste1.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(195, 200);
    w = o;
    { Fl_Pack* o = new Fl_Pack(0, 0, 195, 200);
      { new Fl_Button(0, 0, 66, 20, "button");
      } // Fl_Button* o
      { new Fl_Button(0, 20, 66, 20, "button");
      } // Fl_Button* o
      { new Fl_Button(65, 20, 66, 20, "button");
      } // Fl_Button* o
      { new Fl_Button(130, 0, 65, 40, "button");
      } // Fl_Button* o
      { new Fl_Button(65, 0, 66, 20, "button");
      } // Fl_Button* o
      { new Fl_Input(0, 40, 195, 25);
      } // Fl_Input* o
      { new Fl_Clock(0, 65, 195, 135);
      } // Fl_Clock* o
      o->end();
    } // Fl_Pack* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

int main(int argc, char **argv)
{
    make_window()->show();
    return Fl::run();
}

